const sb=supabase.createClient(APP_CONFIG.SUPABASE_URL,APP_CONFIG.SUPABASE_ANON_KEY);let rows=[],pendingRows=[],payrollPin='';const $=id=>document.getElementById(id),validStatus=['Belum Approve','Area Manager','VP','Direktur','Wewenang Lainnya'];$('period').value=new Date().toISOString().slice(0,7);
function note(t,type='ok'){$('notice').className=type;$('notice').textContent=t}function safe(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function fail(e){note(e.message||String(e),'error')}function locked(){return Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Jakarta',day:'2-digit'}).format(new Date()))>=21}
$('payrollBtn').onclick=()=>{const p=prompt('Masukkan PIN Payroll');if(p!==null){payrollPin=p;note('PIN Payroll tersimpan untuk sesi ini dan akan diverifikasi oleh database saat ada perubahan.')}};
$('uploadBtn').onclick=async()=>{try{const file=$('file').files[0],uploader=$('uploader').value.trim(),period=$('period').value;if(!file||!uploader||!period)throw Error('Uploader, periode, dan file Excel wajib diisi.');const wb=XLSX.read(await file.arrayBuffer()),raw=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});pendingRows=raw.map((r,i)=>{const x={nopeg:String(r.Nopeg).trim(),nama:String(r.Nama).trim(),lokasi:String(r['Lokasi Kerja']).trim(),real:Number(r['Lembur Real']),konversi:Number(r['Lembur Konversi']),approval:String(r['Status Approval']).trim()};if(!x.nopeg||!x.nama||!x.lokasi||!Number.isFinite(x.real)||!Number.isFinite(x.konversi)||!validStatus.includes(x.approval))throw Error(`Baris ${i+2} belum lengkap atau Status Approval tidak sesuai.`);return x});const {data,error}=await sb.rpc('find_overtime_duplicates',{p_period:period,p_rows:pendingRows});if(error)throw error;if(data?.length){$('duplicates').innerHTML=data.map(d=>`<div class="duplicate-item"><b>${safe(d.nopeg)} · ${safe(d.nama)}</b><small>Uploader sebelumnya: ${safe(d.uploader)} · ${formatDate(d.uploaded_at)}</small></div>`).join('');$('duplicateDialog').showModal();return}await save(false)}catch(e){fail(e)}};
async function save(replace){try{const {data,error}=await sb.rpc('save_overtime',{p_period:$('period').value,p_uploader:$('uploader').value.trim(),p_rows:pendingRows,p_replace:replace,p_pin:payrollPin});if(error)throw error;note(`${data.count} data berhasil disimpan.`);pendingRows=[];await loadData()}catch(e){fail(e)}}
$('cancelReplace').onclick=()=>{$('duplicateDialog').close();pendingRows=[];note('Upload dibatalkan karena data sudah pernah di-upload.','error')};$('confirmReplace').onclick=async()=>{$('duplicateDialog').close();await save(true)};
async function loadData(){try{const {data,error}=await sb.rpc('list_overtime',{p_period:$('period').value});if(error)throw error;rows=data||[];$('lockInfo').textContent=`${locked()?'Terkunci sejak tanggal 21':'Terbuka sampai tanggal 20'} · ${rows.length} data`;const locs=['Semua Lokasi',...new Set(rows.map(r=>r.work_location))];$('location').innerHTML=locs.map(v=>`<option>${safe(v)}</option>`).join('');render()}catch(e){fail(e)}}
function render(){const loc=$('location').value,data=loc==='Semua Lokasi'?rows:rows.filter(r=>r.work_location===loc);$('body').innerHTML=data.map(r=>`<tr><td>${safe(r.employee_number)}</td><td>${safe(r.employee_name)}</td><td>${safe(r.work_location)}</td><td>${r.real_overtime}</td><td>${r.converted_overtime}</td><td>${safe(r.approval_status)}</td><td><b>${r.payable_overtime}</b></td><td>${safe(r.uploader)}</td><td>${formatDate(r.uploaded_at)}</td><td><button class="delete" onclick="removeRow('${r.id}','${safe(r.employee_name)}')">Hapus</button></td></tr>`).join('')||'<tr><td colspan="10">Belum ada data.</td></tr>'}
async function removeRow(id,nama){if(!confirm(`Hapus data ${nama}?`))return;const {error}=await sb.rpc('delete_overtime',{p_id:id,p_pin:payrollPin});if(error)return fail(error);note('Data berhasil dihapus dan dapat di-upload ulang.');loadData()}
async function clearDb(){const pin=prompt('Masukkan PIN Payroll untuk mengosongkan seluruh database');if(pin===null||!confirm('Semua data lembur akan dihapus permanen. Pastikan report sudah di-download. Lanjutkan?'))return;const {error}=await sb.rpc('clear_overtime',{p_pin:pin});if(error)return fail(error);note('Database berhasil dikosongkan.');loadData()}
function exportReport(){const loc=$('location').value,data=(loc==='Semua Lokasi'?rows:rows.filter(r=>r.work_location===loc)).map(r=>({Nopeg:r.employee_number,Nama:r.employee_name,'Lokasi Kerja':r.work_location,'Lembur Real':r.real_overtime,'Lembur Konversi':r.converted_overtime,'Status Approval':r.approval_status,'Lembur yang Dapat Dibayarkan':r.payable_overtime,Uploader:r.uploader,'Tanggal Upload':formatDate(r.uploaded_at)})),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(data),'Report Lembur');XLSX.writeFile(wb,`Report-Lembur-${$('period').value}-${loc}.xlsx`)}function formatDate(v){return v?new Date(v).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'}):'—'}
$('showBtn').onclick=loadData;$('exportBtn').onclick=exportReport;$('clearBtn').onclick=clearDb;$('location').onchange=render;$('period').onchange=loadData;loadData();
